# Cloudflare Pages 配置文件

name = "ainstr-mcp-square"
compatibility_date = "2024-01-01"

# Pages 配置
pages_build_output_dir = ".vercel/output/static"

[site]
bucket = ".vercel/output/static"

# 环境变量（可选）
[vars]
NODE_ENV = "production"

# 构建配置在 package.json 中定义

